<?php 

// CONFIG / https://forum.photo.gallery/viewtopic.php?f=66&t=9964
// Uncomment the parameters you want to edit.
return array (
  //'root' => '',
  //'start_path' => false,
  //'username' => '',
  //'password' => '',
  //'load_images' => true,
  //'load_files_proxy_php' => false,
  //'load_images_max_filesize' => 1000000,
  //'load_svg_max_filesize' => 100000,
  //'image_resize_enabled' => true,
  //'image_resize_cache' => true,
  //'image_resize_dimensions' => 320,
  //'image_resize_dimensions_retina' => 480,
  //'image_resize_quality' => 85,
  //'image_resize_function' => 'imagecopyresampled',
  //'image_resize_sharpen' => true,
  //'image_resize_memory_limit' => 128,
  //'image_resize_max_pixels' => 30000000,
  //'image_resize_min_ratio' => 1.5,
  //'image_resize_cache_direct' => false,
  //'menu_enabled' => true,
  //'menu_show' => true,
  //'menu_max_depth' => 5,
  //'menu_sort' => 'name_asc',
  //'menu_cache_validate' => true,
  //'menu_load_all' => false,
  //'menu_recursive_symlinks' => true,
  //'layout' => 'rows',
  //'image_cover' => true,
  //'sort' => 'name_asc',
  //'sort_dirs_first' => true,
  //'cache' => true,
  //'cache_key' => 0,
  //'storage_path' => '_files',
  //'files_exclude' => '',
  //'dirs_exclude' => '',
  //'allow_symlinks' => true,
  //'history' => true,
  //'breadcrumbs' => true,
  //'transitions' => true,
  //'click' => 'popup',
  //'code_max_load' => 100000,
  //'code_allow_edit' => false,
  //'popup_interval' => 5000,
  //'topbar_sticky' => 'scroll',
  //'check_updates' => true,
  //'allow_tasks' => true,
  //'get_mime_type' => false,
  //'context_menu' => true,
  //'prevent_right_click' => false,
  //'license_key' => '',
);